## Name your project
NAME = dennis

MODEL = ebay

MCU       = atmega328p
F_CPU     = 16000000UL
#PORT      = usb
PORT      = /dev/ttyACM0
PROG      = avrispmkII
#PROG_BAUD = 115200
#PROG_BAUD = 19200
#PROG_BAUD = 57600
#MCU       = atmega328p
#F_CPU     = 16000000UL
#PORT      = /dev/ttyUSB0
#PROG      = arduino
#PROG_BAUD = 57600

include ../../Makefile
